"""Initial Migrate

Revision ID: 98b056509567
Revises: 
Create Date: 2024-07-18 16:11:28.334096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b056509567'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixed_acidity', sa.Float(), nullable=True),
    sa.Column('volatile_acidity', sa.Float(), nullable=True),
    sa.Column('critic_acid', sa.Float(), nullable=True),
    sa.Column('residual_sugar', sa.Float(), nullable=True),
    sa.Column('chlorides', sa.Float(), nullable=True),
    sa.Column('free_sulfur_dioxide', sa.Float(), nullable=True),
    sa.Column('total_sulfur_dioxide', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('pH', sa.Float(), nullable=True),
    sa.Column('sulphates', sa.Float(), nullable=True),
    sa.Column('alcohol', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wine')
    # ### end Alembic commands ###
